apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: per-pod-metric
  namespace: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: per-pod-metric
  minReplicas: 1
  maxReplicas: 100
  metrics:
  - type: Pods
    pods:
      metric:
        name: current_connections
      target:
        type: AverageValue
        averageValue: 250
